# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/postgresql.cnpg.io/cluster_v1.json
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-db
spec:
  instances: 1
  enablePDB: false
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4-standard-trixie@sha256:4e4ac3fb2c914cfb44f80f0b8be8aa550e83b80bf5220df49c3a8780c1f79bc8 
  bootstrap:
    recovery:
      source: &externalCluster authentik-db
  storage:
    size: 10Gi
    pvcTemplate:
      storageClassName: ceph-block
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
  superuserSecret:
    name: authentik-pg-superuser-secret
  monitoring:
    enablePodMonitor: true
  enableSuperuserAccess: false
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: authentik-store
  externalClusters:
    - name: *externalCluster
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: authentik-store
          serverName: *externalCluster
