---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: peanut
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: peanut-secret
    template:
      data:
        WEB_USERNAME: "{{ .PEANUT_WEB_USERNAME }}"
        WEB_PASSWORD: "{{ .PEANUT_WEB_PASSWORD }}"
  dataFrom:
    - extract:
        key: peanut
