---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/barmancloud.cnpg.io/objectstore_v1.json
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: ${APP}-store
spec:
  retentionPolicy: 30d
  configuration:
    data:
      compression: bzip2
    wal:
      compression: zstd
      maxParallel: 8
    destinationPath: "s3://home-ops-postgres-backups/${APP}/"
    endpointURL: "http://alderaan.internal:3900"
    s3Credentials:
      accessKeyId:
        name: ${APP}-garage-secret
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: ${APP}-garage-secret
        key: ACCESS_SECRET_KEY
      region:
        name: ${APP}-garage-secret
        key: REGION
