# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/cluster_v1.json
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: dawarich-db
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgis:18.4-3.6.3-system-trixie@sha256:aa9f01e3592c659ea7c870577056be36909720b01a1fb99c6c67db38eb247476 
  bootstrap:
    recovery:
      source: &externalCluster dawarich-db
  storage:
    size: 10Gi
    pvcTemplate:
      storageClassName: ceph-block
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
  superuserSecret:
    name: dawarich-pg-superuser-secret
  monitoring:
    enablePodMonitor: true
  enableSuperuserAccess: false
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: b2-dawarich
  externalClusters:
    - name: *externalCluster
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: b2-dawarich
          serverName: *externalCluster
