# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/postgresql.cnpg.io/cluster_v1.json
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: dawarich-db
spec:
  instances: 1
  enablePDB: false
  imageName: ghcr.io/cloudnative-pg/postgis:18.4-3.6.3-system-trixie@sha256:355c2fde0ca6e0594da856cae1f12e09275e3868d31e84cb7047ecbb387f2cc5 
  bootstrap:
    recovery:
      source: &externalCluster dawarich-db
  storage:
    size: 10Gi
    pvcTemplate:
      storageClassName: ceph-block
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
  superuserSecret:
    name: dawarich-pg-superuser-secret
  monitoring:
    enablePodMonitor: true
  enableSuperuserAccess: false
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: dawarich-store
  externalClusters:
    - name: *externalCluster
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: dawarich-store
          serverName: *externalCluster
