---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dispatcharr-pg-superuser
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
  data:
    - secretKey: dispatcharr-pg-superuser-secret
      remoteRef:
        key: dispatcharr
        property: DISPATCHARR_PG_SUPERUSER_SECRET
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dispatcharr-cluster-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: dispatcharr-cluster-credentials-secret
    template:
      data:
        username: "{{ .DISPATCHARR_POSTGRES_USERNAME }}"
        password: "{{ .DISPATCHARR_POSTGRES_PASSWORD }}"
  dataFrom:
    - extract:
        key: dispatcharr
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dispatcharr-backblaze-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: dispatcharr-backblaze-secret
    template:
      data:
        ACCESS_KEY_ID: "{{ .BACKBLAZE_HOME_OPS_KEY_ID }}"
        ACCESS_SECRET_KEY: "{{ .BACKBLAZE_HOME_OPS_APPLICATION_KEY }}"
  dataFrom:
    - extract:
        key: backblaze
