---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/k8s.cni.cncf.io/networkattachmentdefinition_v1.json
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: trusted
spec:
  config: |-
    {
      "cniVersion": "1.1.0",
      "name": "trusted",
      "plugins": [
        {
          "type": "macvlan",
          "master": "bond0.20",
          "mode": "bridge",
          "ipam": {
            "type": "static"
          }
        }
      ]
    }
