# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/postgresql.cnpg.io/cluster_v1.json
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-db
spec:
  instances: 1
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16.13-1.1.1@sha256:11e4e5a9a45a8b92006a698c7899cd96d22cf74870659db83b462b9a2ecd0d1f
  bootstrap:
    recovery:
      source: &externalCluster immich-database-v2
  storage:
    size: 5Gi
    pvcTemplate:
      storageClassName: ceph-block
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
  superuserSecret:
    name: immich-pg-superuser-secret
  monitoring:
    enablePodMonitor: true
  enableSuperuserAccess: false
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: b2-immich
  externalClusters:
    - name: *externalCluster
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: b2-immich
          serverName: *externalCluster
