# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/postgresql.cnpg.io/cluster_v1.json
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-db
spec:
  instances: 1
  enablePDB: false
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:18.3-1.1.1@sha256:392b53675b403d6a2c72b673cc488a7c272514755dd818c622fb9ce4665193c4
  bootstrap:
    recovery:
      source: &externalCluster immich-db
  storage:
    size: 5Gi
    pvcTemplate:
      storageClassName: ceph-block
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
  superuserSecret:
    name: immich-pg-superuser-secret
  monitoring:
    enablePodMonitor: true
  enableSuperuserAccess: false
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: immich-store
  externalClusters:
    - name: *externalCluster
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: immich-store
          serverName: *externalCluster
