---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-pg-superuser
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
  data:
    - secretKey: immich-pg-superuser-secret
      remoteRef:
        key: immich
        property: IMMICH_POSTGRES_SUPERUSER_SECRET
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-cluster-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: immich-cluster-credentials-secret
    template:
      data:
        username: "{{ .IMMICH_POSTGRES_USERNAME }}"
        password: "{{ .IMMICH_POSTGRES_PASSWORD }}"
  dataFrom:
    - extract:
        key: immich
