---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: authentik-secret
    template:
      data:
        secret_key: "{{ .AUTHENTIK_SECRET_KEY }}"
        smtp_host: "{{ .SMTP_RELAY_HOSTNAME }}"
        username: "{{ .AUTHENTIK_POSTGRES_USERNAME }}"
        password: "{{ .AUTHENTIK_POSTGRES_PASSWORD }}"
  dataFrom:
    - extract:
        key: authentik
    - extract:
        key: smtp-relay
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: authentik-oidc-secret
    template:
      data:
        AUTOBRR_CLIENT_ID: "{{ .AUTOBRR_AUTHENTIK_CLIENT_ID }}"
        AUTOBRR_CLIENT_SECRET: "{{ .AUTOBRR_AUTHENTIK_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: autobrr
