---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: authentik-secret
    template:
      data:
        secret_key: "{{ .AUTHENTIK_SECRET_KEY }}"
        smtp_host: "{{ .SMTP_RELAY_HOSTNAME }}"
        username: "{{ .AUTHENTIK_POSTGRES_USERNAME }}"
        password: "{{ .AUTHENTIK_POSTGRES_PASSWORD }}"
  dataFrom:
    - extract:
        key: authentik
    - extract:
        key: smtp-relay
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: authentik-oidc-secret
    template:
      data:
        AUTOBRR_CLIENT_ID: "{{ .AUTOBRR_AUTHENTIK_CLIENT_ID }}"
        AUTOBRR_CLIENT_SECRET: "{{ .AUTOBRR_AUTHENTIK_CLIENT_SECRET }}"
        CALIBRE_WEB_CLIENT_ID: "{{ .CALIBRE_WEB_AUTOMATED_AUTHENTIK_CLIENT_ID }}"
        CALIBRE_WEB_CLIENT_SECRET: "{{ .CALIBRE_WEB_AUTOMATED_AUTHENTIK_CLIENT_SECRET }}"
        DAWARICH_CLIENT_ID: "{{ .DAWARICH_OIDC_CLIENT_ID }}"
        DAWARICH_CLIENT_SECRET: "{{ .DAWARICH_OIDC_CLIENT_SECRET }}"
        IMMICH_CLIENT_ID: "{{ .IMMICH_AUTHENTIK_CLIENT_ID }}"
        IMMICH_CLIENT_SECRET: "{{ .IMMICH_AUTHENTIK_CLIENT_SECRET }}"
        KARAKEEP_CLIENT_ID: "{{ .KARAKEEP_OIDC_CLIENT_ID }}"
        KARAKEEP_CLIENT_SECRET: "{{ .KARAKEEP_OIDC_CLIENT_SECRET }}"
        QUI_CLIENT_ID: "{{ .QUI_AUTHENTIK_CLIENT_ID }}"
        QUI_CLIENT_SECRET: "{{ .QUI_AUTHENTIK_CLIENT_SECRET }}"
        ROMM_CLIENT_ID: "{{ .ROMM_OIDC_CLIENT_ID }}"
        ROMM_CLIENT_SECRET: "{{ .ROMM_OIDC_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: autobrr
    - extract:
        key: calibre-web-automated
    - extract:
        key: dawarich
    - extract:
        key: immich
    - extract:
        key: karakeep
    - extract:
        key: qui
    - extract:
        key: romm
