---
# yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
version: 1
metadata:
  name: Shelfmark OAuth2 Provider and Application
context:
  authorization_flow: &authorization_flow !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
  invalidation_flow: &invalidation_flow !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
  property_mappings: &property_mappings
    - !Find [authentik_providers_oauth2.scopemapping, [name, "authentik default OAuth Mapping: OpenID 'openid'"]]
    - !Find [authentik_providers_oauth2.scopemapping, [name, "authentik default OAuth Mapping: OpenID 'profile'"]]
    - !Find [authentik_providers_oauth2.scopemapping, [name, "ROMM & Dawarich email_verified fix"]]
  signing_key: &signing_key !Find [authentik_crypto.certificatekeypair, [name, authentik Self-signed Certificate]]
entries:
  - model: authentik_providers_oauth2.oauth2provider
    identifiers:
      name: Provider for Shelfmark
    attrs:
      name: Provider for Shelfmark
      authorization_flow: *authorization_flow
      invalidation_flow: *invalidation_flow
      client_type: confidential
      client_id: !Env SHELFMARK_CLIENT_ID
      client_secret: !Env SHELFMARK_CLIENT_SECRET
      redirect_uris:
        - url: https://shelfmark.martinbjeldbak.com/api/auth/oidc/callback
          matching_mode: strict
      grant_types:
        - authorization_code
        - refresh_token
      property_mappings: *property_mappings
      signing_key: *signing_key

  - model: authentik_core.application
    identifiers:
      slug: shelfmark
    attrs:
      name: Shelfmark
      slug: shelfmark
      provider: !Find [authentik_providers_oauth2.oauth2provider, [name, Provider for Shelfmark]]
      policy_engine_mode: any
      group: Media
      meta_description: Book and audiobook search & request hub
      meta_icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/shelfmark.svg
      open_in_new_tab: false
